### ISSUE TITLE
Package request: BorgBackup

### ISSUE THREAD

**Issue by ClNo** [Entware/Entware-ng#851]
### Package: BorgBackup

https://github.com/borgbackup/borg
https://borgbackup.readthedocs.io/en/stable/installation.html

BorgBackup is a very common backup server and client with a strong encryption (transfer AND storage). It also supports compression and data deduplication which altogether makes it quite unique.

### Platform:
x86_64 (QNAP)

Thanks!

**Comment by thunfischbrot** [comment]
I am in favor!

**Comment by quicktrick** [comment]
[Look here](https://github.com/borgbackup/borg/issues/690) too.  I run `Borg Backup` under `Entware-ng` on `Qnap TS-239 Pro II+` (i686, firmware 4.2.6, 32-bit) and under `Entware-ng-3x` on `Qnap TS-459 Pro` (x86-64, firmware 4.2.6, 64-bit).  `Borg` itself works fine, except `Fuse`. I have the following output while trying to install `borgbackup[fuse]` from the source code:

    Running setup.py (path:/share/MD0_DATA/.qpkg/Entware-ng/tmp/pip-build-11d5a2rh/llfuse/setup.py) egg_info for package llfuse
      Running command python setup.py egg_info
      Package fuse was not found in the pkg-config search path.
      Perhaps you should add the directory containing `fuse.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'fuse' found

though I have

    Package libfuse (2.9.7-1) installed

I think, this is because of lack of the package `libfuse-dev` in Entware's repository.  I'm going to try to  build it from the source code.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
